---
# Build dynamicaly Logo and environment ascii art

- name: 'Set myenv= {{ myenv }} '
  set_fact:
    myenv: "{{ motd_ascii_art_with_environment| default('test') }}"
  delegate_to: 127.0.0.1

- name: Set some internal role vars
  set_fact:
    mybasepath:   "/etc/ansible/roles/ansible.motd/files/"
    mylogofile:   "{{ mybasepath + 'logo' }}"
    mylogo:       "{{ lookup('file', mylogofile, errors='ignore' ) }}"
    myenvfile:    "{{mybasepath + myenv }}"
    myenv:        "{{ lookup('file', myenvfile, errors='ignore' ) }}"
    banner:       "{{ mylogo + myenv }}"
    mybannerfile: "{{ mybasepath }}banner"
  delegate_to: 127.0.0.1

- debug:
    var: '{{ mylogo }}'
  when: mylogo is defined
  delegate_to: 127.0.0.1

- debug:
    var: '{{ myenv }}'
  when: myenv is defined
  delegate_to: 127.0.0.1

- debug:
    var: '{{ banner }}'
  when: banner is defined
  delegate_to: 127.0.0.1
 
- name: Write banner to text file
  copy: 
    content: "{{ banner }}"
    dest: "{{ mybannerfile }}"
  when: banner is defined and mybanner is defined
  delegate_to: 127.0.0.1
