---
# Build dynamicaly Logo and environment ascii art

- stats:
    path: './files/lib'
  register: out

- debug:
    var: {{ out }}
  when: out.path is defined

- find:
         paths:  './'
         file_type: any
         recurse: yes
         patterns: '{{ myenvfile }}'
  register: myitems
  #delegate_to: 127.0.0.1
  
- name: 'Debug some content vars'
  debug: 
    var: {{ myitems }}
   when: myitems is defined
  #delegate_to: 127.0.0.1
 
#- name: 'list log files'
#  debug: var="{{ files_matched_subdirectory.path }}"
#  with_items: "{{ files_matched_subdirectory.files }}"
  #delegate_to: 127.0.0.1

#- name: Write banner to text file
#  copy: 
#    content: "{{ banner }}"
#    dest: "{{ mybannerfile }}"
#  when: banner is defined and mybanner is defined

#- name: 'Debug {{ banner }}'
#  debug:
#    msg: "{{ lookup('file', mybannerfile, errors='strict') }}"
