---
# Build dynamicaly Logo and environment ascii art
-  find:
         paths:  './'
         file_type: any
         recurse: yes
         patterns: 'library'
   register: files_matched_subdirectory
   delegate_to: 127.0.0.1
 
 - name: "list log files"
  debug: var="{{ item.path }}"
  with_items: "{{ files_matched_subdirectory.files }}
  
- name: 'Debug some content vars'
  debug:
    msg: "{{ item.path }}"
  delegate_to: 127.0.0.1

#- name: Write banner to text file
#  copy: 
#    content: "{{ banner }}"
#    dest: "{{ mybannerfile }}"
#  when: banner is defined and mybanner is defined

#- name: 'Debug {{ banner }}'
#  debug:
#    msg: "{{ lookup('file', mybannerfile, errors='strict') }}"
