---
# Build dynamicaly Logo and environment ascii art
-  find:
         paths:  '.'
         file_type: file
         recurse: yes
         use_regex: yes
         patterns:
           - 'library'
   register: files_matched_subdirectory
   delegate_to: 127.0.0.1
 
- name: 'Debug some content vars'
  debug:
    msg: "{{ files_matched_subdirectory | map(attribute='path') | list }}"
  delegate_to: 127.0.0.1

- name: "find directory xyz"
  find:
    paths: "."
    recurse: yes
    file_type: file
    patterns: "library"
  register: find_matches
  delegate_to: 127.0.0.1

- name: "print the path of our first result"
  debug:
    var: find_matches.files[0].path
  when: find_matches is defined


#- name: Write banner to text file
#  copy: 
#    content: "{{ banner }}"
#    dest: "{{ mybannerfile }}"
#  when: banner is defined and mybanner is defined

#- name: 'Debug {{ banner }}'
#  debug:
#    msg: "{{ lookup('file', mybannerfile, errors='strict') }}"
