---
# Build dynamicaly Logo and environment ascii art
-  find:
         paths:  .
         #file_type: {{ myenvfile }}
         recurse: yes
         use_regex: yes
         patterns:
           - 'library'
   register: files_matched_subdirectory
   delegate_to: 127.0.0.1
 
- name: 'Debug some content vars'
  debug:
    msg: "{{ files_matched_subdirectory }}"

#- name: Write banner to text file
#  copy: 
#    content: "{{ banner }}"
#    dest: "{{ mybannerfile }}"
#  when: banner is defined and mybanner is defined

#- name: 'Debug {{ banner }}'
#  debug:
#    msg: "{{ lookup('file', mybannerfile, errors='strict') }}"
