---
# Build dynamicaly Logo and environment ascii art

- name: Write banner to text file
  copy: 
    content: "{{ banner }}"
    dest: "{{ mybannetfile }}"
  when: banner is defined and mybanner is defined
  
#- name: Build vars environment
#  vars:
#    mylogo:  "{{ lookup('file','files/logo.txt') }}"
#    myenv: "{{ lookup('file','files/' + motd_ascii_art_with_environment + '.txt') }}"
#    banner: "{{ mylogo + myenv }}"
#    mybannerfile: "files/banner.txt"



#- debug:
#  msg: "{{ mybanner }}"
