---
# tasks file for arillso.motd

- name: Build ascii art with environment
  include_tasks: build_ascii_art.yml
  when: motd_ascii_art_with_environment|bool == true
  tags:
    - ascii
    - art
    - banner
    - environment

- name: add OS specific variables
  include_vars: '{{ loop_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'defaults.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration
    - packages

- name: add distribution tasks
  include_tasks: '{{ loop_distribution }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'defaults.yml'
      paths:
        - 'distribution'
  loop_control:
    loop_var: loop_distribution
  tags:
    - configuration
